// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hackathon.triptofan.domain;

import hackathon.triptofan.domain.Itenerary;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Itenerary_Roo_Configurable {
    
    declare @type: Itenerary: @Configurable;
    
}
