// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hackathon.triptofan.domain;

import hackathon.triptofan.domain.Tag;

privileged aspect Tag_Roo_JavaBean {
    
    public String Tag.getSubject() {
        return this.subject;
    }
    
    public void Tag.setSubject(String subject) {
        this.subject = subject;
    }
    
}
