// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hackathon.triptofan.domain;

import hackathon.triptofan.domain.Itenerary;
import hackathon.triptofan.domain.IteneraryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect IteneraryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IteneraryDataOnDemand: @Component;
    
    private Random IteneraryDataOnDemand.rnd = new SecureRandom();
    
    private List<Itenerary> IteneraryDataOnDemand.data;
    
    public Itenerary IteneraryDataOnDemand.getNewTransientItenerary(int index) {
        Itenerary obj = new Itenerary();
        setName(obj, index);
        return obj;
    }
    
    public void IteneraryDataOnDemand.setName(Itenerary obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Itenerary IteneraryDataOnDemand.getSpecificItenerary(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Itenerary obj = data.get(index);
        Long id = obj.getId();
        return Itenerary.findItenerary(id);
    }
    
    public Itenerary IteneraryDataOnDemand.getRandomItenerary() {
        init();
        Itenerary obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Itenerary.findItenerary(id);
    }
    
    public boolean IteneraryDataOnDemand.modifyItenerary(Itenerary obj) {
        return false;
    }
    
    public void IteneraryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Itenerary.findIteneraryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Itenerary' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Itenerary>();
        for (int i = 0; i < 10; i++) {
            Itenerary obj = getNewTransientItenerary(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
