// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hackathon.triptofan.domain;

import hackathon.triptofan.domain.Itenerary;
import hackathon.triptofan.domain.IteneraryDataOnDemand;
import hackathon.triptofan.domain.IteneraryIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IteneraryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IteneraryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IteneraryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IteneraryIntegrationTest: @Transactional;
    
    @Autowired
    IteneraryDataOnDemand IteneraryIntegrationTest.dod;
    
    @Test
    public void IteneraryIntegrationTest.testCountItenerarys() {
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", dod.getRandomItenerary());
        long count = Itenerary.countItenerarys();
        Assert.assertTrue("Counter for 'Itenerary' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IteneraryIntegrationTest.testFindItenerary() {
        Itenerary obj = dod.getRandomItenerary();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to provide an identifier", id);
        obj = Itenerary.findItenerary(id);
        Assert.assertNotNull("Find method for 'Itenerary' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Itenerary' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IteneraryIntegrationTest.testFindAllItenerarys() {
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", dod.getRandomItenerary());
        long count = Itenerary.countItenerarys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Itenerary', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Itenerary> result = Itenerary.findAllItenerarys();
        Assert.assertNotNull("Find all method for 'Itenerary' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Itenerary' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IteneraryIntegrationTest.testFindIteneraryEntries() {
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", dod.getRandomItenerary());
        long count = Itenerary.countItenerarys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Itenerary> result = Itenerary.findIteneraryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Itenerary' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Itenerary' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IteneraryIntegrationTest.testFlush() {
        Itenerary obj = dod.getRandomItenerary();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to provide an identifier", id);
        obj = Itenerary.findItenerary(id);
        Assert.assertNotNull("Find method for 'Itenerary' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyItenerary(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Itenerary' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IteneraryIntegrationTest.testMergeUpdate() {
        Itenerary obj = dod.getRandomItenerary();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to provide an identifier", id);
        obj = Itenerary.findItenerary(id);
        boolean modified =  dod.modifyItenerary(obj);
        Integer currentVersion = obj.getVersion();
        Itenerary merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Itenerary' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IteneraryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", dod.getRandomItenerary());
        Itenerary obj = dod.getNewTransientItenerary(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Itenerary' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Itenerary' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IteneraryIntegrationTest.testRemove() {
        Itenerary obj = dod.getRandomItenerary();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Itenerary' failed to provide an identifier", id);
        obj = Itenerary.findItenerary(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Itenerary' with identifier '" + id + "'", Itenerary.findItenerary(id));
    }
    
}
